-- Liftoff: project team leads seed.
-- GENERATED by scripts/seed/generate-team-leads-seed.mjs from design/roadmap-mock.html
-- (mtRoster). Do not edit by hand; regenerate instead.

insert into public.people (display_name, email)
select v.name, v.email
from (values
  ('Connor Walsh', 'connor.walsh@ibm.com'),
  ('Emily Chen', 'emily.chen@ibm.com'),
  ('Hiro Sato', 'hiro.sato@ibm.com'),
  ('Kwame Asante', 'kwame.asante@ibm.com'),
  ('Lucas Dubois', 'lucas.dubois@ibm.com'),
  ('Maya Levi', 'maya.levi@ibm.com'),
  ('Raj Patel', 'raj.patel@ibm.com'),
  ('Sofia Ivanova', 'sofia.ivanova@ibm.com'),
  ('Tyler Brooks', 'tyler.brooks@ibm.com'),
  ('Zoe Williams', 'zoe.williams@ibm.com')
) as v(name, email)
where not exists (select 1 from public.people pe where lower(pe.display_name) = lower(v.name));

update public.project_teams pt
set lead_person_id = pe.id
from (values
  ('CW-1042', 'Firmware', 'Hiro Sato'),
  ('CW-1042', 'Kernel', 'Kwame Asante'),
  ('CW-1067', 'Firmware', 'Tyler Brooks'),
  ('CW-1088', 'Platform', 'Sofia Ivanova'),
  ('CW-1088', 'SRE', 'Connor Walsh'),
  ('CW-1103', 'AI Infra', 'Kwame Asante'),
  ('CW-1103', 'Kernel', 'Emily Chen'),
  ('CW-1115', 'Platform', 'Raj Patel'),
  ('CW-1115', 'Tooling', 'Maya Levi'),
  ('CW-1121', 'Security', 'Zoe Williams'),
  ('CW-1130', 'SRE', 'Zoe Williams'),
  ('CW-1130', 'Firmware', 'Tyler Brooks'),
  ('CW-1144', 'Platform', 'Kwame Asante'),
  ('CW-1144', 'SRE', 'Emily Chen'),
  ('CW-1150', 'AI Infra', 'Tyler Brooks'),
  ('CW-1158', 'Tooling', 'Tyler Brooks'),
  ('CW-1158', 'SRE', 'Hiro Sato'),
  ('CW-1163', 'Platform', 'Lucas Dubois'),
  ('CW-1171', 'Storage', 'Zoe Williams'),
  ('CW-1180', 'Platform', 'Maya Levi'),
  ('CW-1186', 'Tooling', 'Emily Chen'),
  ('CW-1186', 'AI Infra', 'Zoe Williams'),
  ('CW-1192', 'Platform', 'Emily Chen'),
  ('CW-1192', 'Tooling', 'Raj Patel'),
  ('CW-1197', 'Security', 'Sofia Ivanova'),
  ('CW-1197', 'Network', 'Emily Chen'),
  ('CW-1204', 'SRE', 'Maya Levi'),
  ('CW-1204', 'Network', 'Sofia Ivanova'),
  ('CW-1210', 'Firmware', 'Tyler Brooks'),
  ('CW-1210', 'Security', 'Hiro Sato'),
  ('CW-1218', 'Tooling', 'Sofia Ivanova'),
  ('CW-1223', 'Storage', 'Connor Walsh'),
  ('CW-1229', 'SRE', 'Zoe Williams'),
  ('CW-1234', 'Compliance', 'Tyler Brooks'),
  ('CW-1234', 'Security', 'Zoe Williams'),
  ('CW-1240', 'AI Infra', 'Kwame Asante'),
  ('CW-1240', 'Platform', 'Tyler Brooks'),
  ('CW-1247', 'Network', 'Connor Walsh'),
  ('CW-1255', 'Kernel', 'Emily Chen'),
  ('CW-1255', 'SRE', 'Lucas Dubois'),
  ('CW-1262', 'AI Infra', 'Kwame Asante'),
  ('CW-1262', 'Tooling', 'Sofia Ivanova'),
  ('CW-1270', 'Platform', 'Raj Patel'),
  ('CW-1270', 'SRE', 'Kwame Asante'),
  ('CW-1277', 'Security', 'Kwame Asante'),
  ('CW-1290', 'Compliance', 'Maya Levi'),
  ('CW-1290', 'Firmware', 'Hiro Sato'),
  ('CW-1296', 'Platform', 'Raj Patel'),
  ('CW-1296', 'Network', 'Kwame Asante'),
  ('CW-1308', 'SRE', 'Emily Chen'),
  ('CW-1308', 'Tooling', 'Raj Patel'),
  ('CW-1330', 'Platform', 'Lucas Dubois'),
  ('CW-1283', 'Kernel', 'Tyler Brooks'),
  ('CW-1283', 'Storage', 'Sofia Ivanova'),
  ('CW-1301', 'Security', 'Raj Patel'),
  ('CW-1315', 'Tooling', 'Hiro Sato'),
  ('CW-1322', 'Firmware', 'Kwame Asante'),
  ('CW-1322', 'SRE', 'Tyler Brooks'),
  ('CW-1341', 'Platform', 'Emily Chen'),
  ('CW-1341', 'Kernel', 'Maya Levi'),
  ('CW-1347', 'AI Infra', 'Tyler Brooks'),
  ('CW-1347', 'Tooling', 'Connor Walsh'),
  ('CW-1352', 'Security', 'Zoe Williams'),
  ('CW-1352', 'SRE', 'Emily Chen'),
  ('CW-1358', 'Storage', 'Emily Chen')
) as v(project_key, team_name, lead_name)
join public.projects p on p.key = v.project_key
join public.teams t on t.name = v.team_name
join public.people pe on lower(pe.display_name) = lower(v.lead_name)
where pt.project_id = p.id and pt.team_id = t.id;
